# Generated by Django 3.2.23 on 2023-12-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cradle', '0002_sensordata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='user',
        ),
    ]
